backstage/views/analysis.py
from flask import render_template, Blueprint
from flask_login import LoginManager, UserMixin, login_user, logout_user, login_required, current_user
from link import *
from api.sql import Analysis

analysis = Blueprint('analysis', __name__, template_folder='../templates')

@analysis.route('/dashboard')
@login_required
def dashboard():
    revenue = []
    dataa = []
    for i in range(1,13):
        if i < 10:
            input = "0" + str(i)
        else:
            input = str(i)
        
        row = Analysis.month_price(input)

        if not row:
            revenue.append(0)
        else:
            for j in row:
                revenue.append(j[1])
        
        if i < 10:
            input = "0" + str(i)
        else:
            input = str(i)
            
        row = Analysis.month_count(input)
        
        if not row:
            dataa.append(0)
        else:
            for k in row:
                dataa.append(k[1])
        
    row = Analysis.category_sale()
    datab = []
    for i in row:
        temp = {
            'value': i[0],
            'name': i[1]
        }
        datab.append(temp)
    
    row = Analysis.member_sale('user')
    
    datac = []
    nameList = []
    counter = 0
    
    for i in row:
        counter = counter + 1
        datac.append(i[0])
    for j in row:
        nameList.append(j[2])
    
    counter = counter - 1
    
    row = Analysis.member_sale_count('user')
    countList = []
    
    for i in row:
        countList.append(i[0])
        
    return render_template('dashboard.html', counter = counter, revenue = revenue, dataa = dataa, datab = datab, datac = datac, nameList = nameList, countList = countList, user = current_user.name)

backstage/views/manager.py
from flask import Blueprint, render_template, request, url_for, redirect
from flask_login import LoginManager, UserMixin, login_user, logout_user, login_required, current_user
from link import *
from api.sql import *
import imp, random, os, string
from werkzeug.utils import secure_filename
from flask import current_app, flash

UPLOAD_FOLDER = os.path.abspath(os.curdir) + '/static/product/'
ALLOWED_EXTENSIONS = set(['png', 'jpg', 'jpeg'])

manager = Blueprint('manager', __name__, template_folder='../templates')

def config():
    current_app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER
    config = current_app.config['UPLOAD_FOLDER']
    return config

@manager.route('/', methods=['GET', 'POST'])
@login_required
def home():
    return redirect(url_for('manager.productManager'))

@manager.route('/productManager', methods=['GET', 'POST'])
@login_required
def productManager():
    if request.method == 'GET':
        if(current_user.role == 'user'):
            flash('No permission')
            return redirect(url_for('index'))
        
    if 'delete' in request.values:
        pid = request.values.get('delete')
        data = Shopping_Detail.delete_check(pid)
        
        if(data != None):
            flash('failed')
        else:
            data = Product.get_product(pid)
            image = data[5]
            if(image != None):
                os.remove(os.path.join(config(), image))
                
            Product.delete_product(pid)
    
    elif 'edit' in request.values:
        pid = request.values.get('edit')
        return redirect(url_for('manager.edit', pid=pid))
    
    book_data = book()
    return render_template('productManager.html', book_data = book_data, user=current_user.name)

def book():
    book_row = Product.get_all_product()
    book_data = []
    for i in book_row:
        book = {
            '商品編號': i[0],
            '商品名稱': i[1],
            '商品售價': i[2],
            '商品類別': i[3]
        }
        book_data.append(book)
    return book_data

@manager.route('/add', methods=['GET', 'POST'])
def add():
    if request.method == 'POST':
        data = ""
        while(data != None):
            number = str(random.randrange( 10000, 99999))
            en = random.choice(string.ascii_letters)
            pid = en + number
            data = Product.get_product(pid)

        name = request.values.get('name')
        price = request.values.get('price')
        category = request.values.get('category')
        description = request.values.get('description')
        file = request.files['file']
        
        filename = secure_filename(file.filename)
        file.save(os.path.join(config(), filename))
        
        pic = pid + filename[filename.index("."):]
        os.chdir(config())
        os.rename(filename, pic)

        if (len(name) < 1 or len(price) < 1):
            return redirect(url_for('manager.productManager'))
        
        Product.add_product(
            {'pid' : pid,
             'name' : name,
             'price' : price,
             'category' : category,
             'description':description,
             'filename':pic
            }
        )

        return redirect(url_for('manager.productManager'))

    return redirect(url_for('manager.productManager'))

@manager.route('/edit', methods=['GET', 'POST'])
@login_required
def edit():
    if request.method == 'GET':
        if(current_user.role == 'user'):
            flash('No permission')
            return redirect(url_for('index'))

    if request.method == 'POST':

        new_file = request.files['file']
        pid = request.values.get('pid')
        pname = request.values.get('name')
        price = request.values.get('price')
        category = request.values.get('category')
        description = request.values.get('description')
        
        if new_file:
            data = Product.get_product(pid)
            image = data[5]
            if image:
                os.remove(os.path.join(config(), image))
            
            filename = secure_filename(new_file.filename)
            new_file.save(os.path.join(config(), filename))
            pic = pid + filename[filename.index("."):]
            os.chdir(config())
            os.rename(filename, pic)
            
            input = (pname, price, category, description, pid)
            Product.update_product(input)
            
            img = (pic, pid)
            Product.update_image(img)
        
        else:
            input = (pname, price, category, description, pid)
            Product.update_product(input)
        
        return redirect(url_for('manager.productManager'))

    else:
        product = show_info()
        return render_template('edit.html', data=product)


def show_info():
    pid = request.args['pid']
    data = Product.get_product(pid)
    pname = data[1]
    price = data[2]
    category = data[3]
    description = data[4]
    image = data[5]

    product = {
        '商品編號': pid,
        '商品名稱': pname,
        '單價': price,
        '類別': category,
        '商品敘述': description,
        '商品圖片': image
    }
    return product


@manager.route('/orderManager', methods=['GET', 'POST'])
@login_required
def orderManager():
    if request.method == 'POST':
        pass
    else:
        order_row = Order_List.get_order()
        order_data = []
        for i in order_row:
            order = {
                '訂單編號': i[0],
                '訂購人': i[1],
                '訂單總價': i[2],
                '訂單時間': i[3]
            }
            order_data.append(order)
            
        orderdetail_row = Order_List.get_orderdetail()
        order_detail = []

        for j in orderdetail_row:
            orderdetail = {
                '訂單編號': j[0],
                '商品名稱': j[1],
                '商品單價': j[2],
                '訂購數量': j[3]
            }
            order_detail.append(orderdetail)

    return render_template('orderManager.html', orderData = order_data, orderDetail = order_detail, user=current_user.name)

backstage/templates/backstage.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link href="../static/offcanvas.css" rel="stylesheet">
    <link rel="icon" href="../static/img/weblogo.ico" type="image/x-icon">
    <script src="../static/offcanvas.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/echarts/5.1.2/echarts.min.js" integrity="sha512-ppWbHq6q2f7HAwS481w6qikuC0XEeBnmkRg6KWnWg3zSIbJwWWBgsCDMAxzSB7SVqXzWwSYQ2s8TSJKjnaikMg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/dataTables.bootstrap5.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/dataTables.bootstrap5.min.js"></script>
    <title> {% block title%}{% endblock title%} </title>
    {% endblock head %}
</head>

<style>
    main > .container {
        padding: 60px 15px 0;
      }
    
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }
  
    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
  </style>
<body class="bg-light">
    <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark" aria-label="Main navigation">
        <div class="container-fluid">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="white" class="bi bi-easel2" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M8 0a.5.5 0 0 1 .447.276L8.81 1h4.69A1.5 1.5 0 0 1 15 2.5V11h.5a.5.5 0 0 1 0 1h-2.86l.845 3.379a.5.5 0 0 1-.97.242L12.11 14H3.89l-.405 1.621a.5.5 0 0 1-.97-.242L3.36 12H.5a.5.5 0 0 1 0-1H1V2.5A1.5 1.5 0 0 1 2.5 1h4.691l.362-.724A.5.5 0 0 1 8 0ZM2 11h12V2.5a.5.5 0 0 0-.5-.5h-11a.5.5 0 0 0-.5.5V11Zm9.61 1H4.39l-.25 1h7.72l-.25-1Z"/>
            </svg>
            <a class="navbar-brand" href="#">&nbsp;中山網路書店後台管理系統</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('manager.productManager') }}">商品管理</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('manager.orderManager') }}">訂單管理</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('analysis.dashboard') }}">資料分析</a>
                    </li>
                </ul>



                <ul class="navbar-nav me-3 mb-2 mb-lg-0">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="white" class="bi bi-person-circle" viewBox="0 0 18 18">
                        <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                        <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
                    </svg>
                    <li style="color:white;list-style-type:none">管理者：{{user}}</li>
                </ul>
                <div class="d-flex">
                <a href="{{ url_for('api.logout') }}"><button class="btn btn-outline-danger" type="submit">登出系統</button></a>
                </div>
            </div>
        </div>
    </nav>
    <br/><br/>
    {% block content %}
    {% endblock content %}
</body>
</html>

backstage/templates/dashboard.html
{% extends "backstage.html" %}
{% block head %}
{{ super() }}
{% endblock head %}
{% block title %}後台資料分析{% endblock title%}
{% block content %}

<div class="my-3 p-3 bg-body rounded shadow-sm">
  <!-- Dashboard -->
  <div id="dashboard">
    <nav>
      <div class="nav nav-tabs" id="nav-tab" role="tablist">
        <button class="nav-link active" id="nav-home-tab" data-bs-toggle="tab" data-bs-target="#nav-home" type="button" role="tab" aria-controls="nav-home" aria-selected="true">訂單數量分析</button>
        <button class="nav-link" id="nav-profile-tab" data-bs-toggle="tab" data-bs-target="#nav-profile" type="button" role="tab" aria-controls="nav-profile" aria-selected="false">書本銷量分類</button>
        <button class="nav-link" id="nav-contact-tab" data-bs-toggle="tab" data-bs-target="#nav-contact" type="button" role="tab" aria-controls="nav-contact" aria-selected="false">消費總額排名</button>        
      </div>      
    </nav>
  </div>
  <br/>
  <div class="tab-content" id="nav-tabContent">
    <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
      <center> 
        <div id="maina" class="container-fluid" style="width:1200px;height:500px"></div>
      </center>
    </div>
    <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
      <center>
        <div id="mainb" class="container-fluid" style="width: 600px;height:500px"></div>
      </center>
    </div>
    <div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">
      <center>
        <div id="mainc" class="container-fluid" style="width: 1200px;height:500px"></div>
      </center>
    </div>
  </div>
</div>

<script>
  // 以長條圖與折線圖分析各月訂單
  var chartDoma = document.getElementById('maina');
  var myCharta = echarts.init(chartDoma);
  var data = {{revenue|tojson}};
  var count = {{dataa|tojson}};
  var optiona = {
    title: {
      text: '各月銷售總額分析'
    },
    tooltip: {},
    legend: {
      data: ['訂單數量']
    },
    xAxis: {
      data: ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月']
    },
    yAxis: {},
    series: [{
      name: '銷售總額',
      type: 'bar',
      symbolSize: 16,
      data: data,
      markPoint: {
        data: [
          {type: 'max', name: '銷量最高月份'},
          {type: 'min', name: '銷量最低月份'}
        ]
      },
      label: {
        show: true,
        position: 'top',
        textStyle: {
          fontSize: 15
        }
      }
    },
    {
      name: '訂單總數',
      type: 'bar',
      symbolSize: 16,
      data: count,
      markPoint: {
        data: [
          {type: 'max', name: '訂單數最高月份'},
          {type: 'min', name: '訂單數最低月份'}
        ]
      },
      label: {
        show: true,
        position: 'top',
        textStyle: {
          fontSize: 15
        }
      }
    }
    ],
    legend: {
      show: true
    },
  };

  // 以圓餅圖分析書本銷量
  var chartDomb = document.getElementById('mainb');
  var myChartb = echarts.init(chartDomb);
  var data = {{datab|tojson}};
  var optionb = {
    title: {
      text: '各類商品銷量分析',
      left: 'center',
      top: 'center'
    },
    tooltip: {},
    legend: {
      orient: 'vertical',
      x: 'left',
      data: ['BOOK', 'CD', 'DVD']
    },
    series: [
      {
        type: 'pie',
        data: data,          
        radius: ['40%', '70%']
      }
    ]
  };

  // 使用動態長條圖查看消費總額最多的使用者
  var chartDomc = document.getElementById('mainc');
  var myChartc = echarts.init(chartDomc);
  var data = {{datac|tojson}};
  var nameList = {{nameList|tojson}};
  // var counter = {{counter|tojson}};
  var countList = {{countList|tojson}};
  var optionc = {
    title: {
      text: '使用者消費排名'
    },
    xAxis: {
      max: 'dataMax'
    },
    yAxis: {
      type: 'category',
      data: nameList,
      inverse: true,
      animationDuration: 300,
      animationDurationUpdate: 300,
      max: 3
    },
    tooltip: {},
    series: [
      {
        realtimeSort: true,
        name: '消費總額',
        type: 'bar',
        data: data,
        label: {
          show: true,
          position: 'right',
          valueAnimation: true
        }
      },
      {
        realtimeSort: true,
        name: '訂單總數',
        type: 'bar',
        data: countList,
        label: {
          show: true,
          position: 'right',
          valueAnimation: true
        }
      }
      ],
    legend: {
      show: true
    },
    animationDuration: 3000,
    animationDurationUpdate: 3000,
    animationEasing: 'linear',
    animationEasingUpdate: 'linear'
  };

  function run() {
    myChartc.setOption({
      series: [
        {
          type: 'bar',
          data
        }
      ]
    });
  }

  setTimeout(function() {
    run();
  }, 0);
        
  setInterval(function() {
    update();
  }, 3000);

  optiona && myCharta.setOption(optiona);
  optionb && myChartb.setOption(optionb);
  optionc && myChartc.setOption(optionc);
      
</script>

{% endblock content %}

backstage/templates/edit.html
{% extends "backstage.html" %}
{% block head %}
{{ super() }}

{% endblock head %}

{% block title %}BookStore{% endblock title%}

{% block content%}


<br/>
<div class="container-xl">
  <br/>
  <form method="post" enctype=multipart/form-data action={{ url_for('manager.edit') }}>
    <table class="table table-bordered">
      <tr>
        <th>商品編號</th>
        <td><input class="form-control" type="text" value="{{ data.商品編號 }}" name="pid" readonly class="id_input"></td>
      </tr>
      <tr>
        <th>商品名稱</th>
        <td><input class="form-control" type="text" value="{{ data.商品名稱 }}" name="name" required></td>
      </tr>
      <tr>
        <th>單價</th>
        <td><input class="form-control" type="text" value="{{ data.單價 }}" name="price" required></td>
      </tr>
      <tr>
        <th>類別</th>
        <td>
          <select class="form-control" name="category">
            {% if data.類別 == 'CD' %}
              <option value="BOOK">BOOK</option>
              <option value="DVD">DVD</option>
              <option value="CD" selected>CD</option>
            {% elif data.類別 == 'DVD' %}
              <option value="BOOK">BOOK</option>
              <option value="DVD" selected>DVD</option>
              <option value="CD">CD</option>
            {% else %}
              <option value="BOOK" selected>BOOK</option>
              <option value="DVD">DVD</option>
              <option value="CD">CD</option>
            {% endif %}
            
        </select>
      </tr>
      <tr>
        <th>商品敘述</th>
        <td>
          <textarea class="form-control" name="description">{{ data.商品敘述 }}</textarea>
        </td>
      </tr>
      <tr>
        <th>商品圖片</th>
        <td>
          <input type="file" name="file" id="file-uploader" data-target="file-uploader"/>
        </td>
      </tr>
    </table>
    <center>
      <div class="option">
        <button class="btn btn-outline-success" type="submit">確定修改</button> 
        <a href="{{ url_for('manager.productManager') }}"><button class="btn btn-outline-danger">回商品管理</button></a>
      </div>
    </center>

  </form>
</div>



{% endblock content%}

backstage/templates/manager.html
{% extends "backstage.html" %}
{% block head %}
{{ super() }}
{% endblock head %}

{% block title %}BookStore{% endblock title%}

{% block content%}
<div class="btn_div">
  <h1 class="book_title left">31 Lab Book Store</h1>
  <a href="{{ url_for('analysis.dashboard') }}"  title="資料分析"><img class="cart" src="{{ url_for('static', filename='./img/dashboard.png') }}"></a>
  <a href="{{ url_for('logout') }}"  title="登出"><img class="logout" src="{{ url_for('static', filename='./img/logout.png') }}"></a>
</div>
<div class="btn_div">
  <p class="welcome">歡迎 , 管理者：{{user}}</p>
</div>
{% with messages = get_flashed_messages() %}
{% if messages[0] == 'No permission' %}
  
<script language="javascript">

  alert('您沒有使用者的權限喔！');

</script>

{% endif %}
{% endwith %}

{% with messages = get_flashed_messages() %}
{% if messages[0] == 'faild' %}
  
<script language="javascript">

  alert('有使用者有使用到這筆資料，所以不能刪除');

</script>

{% endif %}
{% endwith %}

<div class="book_table">
  <form method='post' action={{ url_for('manager') }} >
    <table cellpadding="10" border='3'>
      <tr>
        <th>商品編號</th>
        <th>商品名稱</th>
        <th>商品售價</th>
        <th>商品類別</th>
        <th></th>
        <th></th>
      </tr>
      {% for book in book_data %}
      <tr>
        <td> {{ book.商品編號 }}</td>
        <td> {{ book.商品名稱 }}</td>
        <td> {{ book.商品售價 }}</td>
        <td> {{ book.商品類別 }}</td>
        <td>
          <button type="submit" value="{{book.商品編號}}" name="edit">修改
          </button>
        </td>
        <td>
          <button type="submit" value="{{book.商品編號}}" name="delete" onclick="return (confirm('你確定要刪除 \'{{ book.商品名稱 }}\' 嗎？'))">
            刪除
          </button>
        </td>
      </tr>
      {% endfor %}
    </table>
      <div class="book_table">
        <a href={{ url_for('add')}}><button value="new" name="new" type="button"> 上架新商品</button></a>
      </div>
    </form>

</div>

{% endblock content%}

backstage/templates/productManager.html
{% extends "backstage.html" %}
{% block head %}
{{ super() }}
{% endblock head %}

{% block title %} 商品管理 {% endblock title %}

{% block content %}

{% with messages = get_flashed_messages() %}
{% if messages[0] == 'No permission' %}
  
<script language="javascript">

  alert('您沒有使用者的權限喔！');

</script>


{% endif %}
{% endwith %}

{% with messages = get_flashed_messages() %}
{% if messages[0] == 'failed' %}
  
<script language="javascript">

  alert('有使用者有使用到這筆資料，所以不能刪除');

</script>

{% endif %}
{% endwith %}

<script>
    $(document).ready(function(){
        $("#keyword").on("keyup", function() {
            var value = $(this).val().toLowerCase();
            $("#product tr").filter(function() {
            $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });
    });
</script>

<br/>
<div class="d-flex col-sm-4">
    <span class="input-group-text" id="basic-addon1">
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
        <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
      </svg>
    </span>
    <input class="form-control me-2" id="keyword" placeholder="搜尋商品" aria-label="Search">
</div>
<br/>
&nbsp;
<button type="button" class="btn btn-outline-success" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
    新增商品
</button>
<form method="post" enctype=multipart/form-data action={{ url_for('manager.add') }}>
    <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="staticBackdropLabel">新增商品</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="mb-3">
                        <label for="inputProductName" class="form-label">商品名稱</label>
                        <input type="text" class="form-control" id="inputProductName" name="name" required>
                    </div>
                    <div class="mb-3">
                        <label for="inputUnitPrice" class="form-label">商品單價</label>
                        <input type="number" class="form-control" id="inputUnitPrice" name="price" required>
                    </div>
                    <div class="mb-3">
                        <label for="inputProductCategory" class="form-label">商品種類</label>
                        <select id="inputProductCategory" class="form-select" name="category" required>
                            <option selected disabled value="">請選擇類型</option>
                            <option value="BOOK">BOOK</option>
                            <option value="CD">CD</option>
                            <option value="DVD">DVD</option>
                        </select>
                    </div>
                    <div class="mb-3">
                        <label for="inputProductDesc" class="form-label">商品敘述</label>
                        <textarea class="form-control" id="inputProductDesc" name="description" required></textarea>
                    </div>
                    <div class="mb-3">
                        <label for="inputProductImg" class="form-label">商品圖片</label><br/>
                        <input type="file" name="file" id="file-uploader" data-target="file-uploader" required/>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-bs-dismiss="modal">取消</button>
                    <button type="submit" class="btn btn-success">確定新增</button>
                </div>
            </div>
        </div>
    </div>
</form>

<br/>

<div class="container-xxl">

<form method='post' action={{ url_for('manager.productManager') }} >
<table id="manager" class="table table-bordered">
    <thead>
        <tr>
            <th width="10%"><center>商品編號</center></th>
            <th width="20%"><center>商品名稱</center></th>
            <th width="15%"><center>商品單價</center></th>
            <th width="15%"><center>商品類別</center></th>
            <th colspan="3"><center>資料操作</center></th>
        </tr>
    </thead>
    <tbody id="product">
    {% for i in book_data %}
        <tr>
            <td><center>{{ i.商品編號 }}</center></td>
            <td><center>{{ i.商品名稱 }}</center></td>
            <td><center>{{ i.商品售價 }}</center></td>
            <td><center>{{ i.商品類別 }}</center></td>
            <!-- <td><center>
                <button type="button" class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#staticBackdrop{{i.商品編號}}">
                    商品資訊
                </button>
            </center></td> -->
            <td><center><button type="submit" value="{{i.商品編號}}" name="edit" class="btn btn-outline-success">編輯商品</button></center></td>
            <td><center><button type="submit" value="{{i.商品編號}}" name="delete" onclick="return (confirm('你確定要刪除 \'{{ i.商品名稱 }}\' 嗎？'))" class="btn btn-outline-danger">刪除商品</button></center></td>
        </tr>
    {% endfor %}
    </tbody>
    
</table>
</form>


</div>

<script>
    function have_product(){
      alert('有使用者有使用到這筆資料，所以不能刪除');
    }
</script>

{% endblock content %}