bookstore/views/views.py
import re, math, random, string
from typing_extensions import Self
from flask import Flask, request, render_template, template_rendered, Blueprint, url_for, redirect, flash
from flask_login import LoginManager, UserMixin, login_user, logout_user, login_required, current_user
from datetime import datetime
from numpy import identity, product
from sqlalchemy import null
from link import *
from api.sql import Member, Order_List, Product, Shopping_Detail, Cart

store = Blueprint('bookstore', __name__, template_folder='../templates')

@store.route('/', methods=['GET', 'POST'])
@login_required
def bookstore():
    maximum = 9
    result = Product.count()
    pagenum = math.ceil(result[0]/9)
    page = 1
    param = 0
    endpoint = 0
    if request.method == 'GET':
        if(current_user.role == 'manager'):
            flash('No permission')
            return redirect(url_for('index'))

    if 'keyword' in request.args and 'page' in request.args:
        total = 0
        flag = 1
        page = int(request.args['page'])
        start = (page - 1) * 9
        end = page * 9
        search = request.values.get('keyword')
        keyword = search
        
        book_row = Product.search(keyword)
        book_data = []
        final_data = []
        
        for i in book_row:
            book = {
                '商品編號': i[0],
                '商品名稱': i[1],
                '商品價格': i[2]
            }
            book_data.append(book)
            total = total + 1
        
        if(len(book_data) < end):
            end = len(book_data)
            endpoint = 1
            
        for j in range(start, end):
            final_data.append(book_data[j])
            
        pagenum = math.ceil(total/9)
        
        return render_template('bookstore.html', flag=flag, keyword=search, book_data=final_data, user=current_user.name, page=page, endpoint=endpoint, pagenum=pagenum)    
        
    elif 'keyword' in request.args:
        flag = 1
        search = request.values.get('keyword')
        keyword = search
        book_row = Product.search(keyword)
        book_data = []
        final_data = []
        total = 0
        
        for i in book_row:
            book = {
                '商品編號': i[0],
                '商品名稱': i[1],
                '商品價格': i[2]
            }

            book_data.append(book)
            total = total + 1

        if len(book_data) < maximum:
            endpoint = 1
        
        pagenum = math.ceil(total/9)   
        
        for i in book_row:
            book = {
                '商品編號': i[0],
                '商品名稱': i[1],
                '商品價格': i[2]
            }
            if len(final_data) < maximum:
                final_data.append(book)
        
        
        return render_template('bookstore.html', keyword=search, flag=flag, book_data=final_data, user=current_user.name, page=page, endpoint=endpoint, pagenum=pagenum)    
    
    elif 'page' in request.args:
        page = int(request.args['page'])
        start = (page - 1) * 9
        end = page * 9
        
        book_row = Product.get_all_product()
        book_data = []
        final_data = []
        
        for i in book_row:
            pid = i[0]
            pname = i[1]
            price = i[2]
            
            book = {
                '商品編號': pid,
                '商品名稱': pname,
                '商品價格': price
            }
            book_data.append(book)
            
        if(len(book_data) < end):
            end = len(book_data)
            endpoint = 1
            
        for j in range(start, end):
            final_data.append(book_data[j])
        
        return render_template('bookstore.html', book_data=final_data, user=current_user.name, page=page, endpoint=endpoint, pagenum=pagenum)    

    elif 'pid' in request.args:
        pid = request.args['pid']
        data = Product.get_product(pid)
        
        pname = data[1]
        price = data[2]
        category = data[3]
        description = data[4]
        image = data[5]
        
        if image == None:
            image = 'sdg.jpg'
        
        product = {
            '商品編號': pid,
            '商品名稱': pname,
            '單價': price,
            '類別': category,
            '商品敘述': description,
            '商品圖片': image
        }

        return render_template('product.html', data = product)
      
    else:
        book_row = Product.get_all_product()
        book_data = []
        for i in book_row:
            pid = i[0]
            pname = i[1]
            price = i[2]
            pic = i[5]
            
            book = {
                '商品編號': pid,
                '商品名稱': pname,
                '商品價格': price,
                '商品圖片': pic
            }
            if len(book_data) < maximum:
                book_data.append(book)
        
        return render_template('bookstore.html', book_data=book_data, user=current_user.name, page=page, endpoint=endpoint, pagenum=pagenum)

# 會員購物車
@store.route('/cart', methods=['GET', 'POST'])
@login_required # 使用者登入後才可以看
def cart():

    # 以防管理者誤闖
    if request.method == 'GET':
        if( current_user.role == 'manager'):
            flash('No permission')
            return redirect(url_for('index'))

    # 回傳有 pid 代表要 加商品
    if request.method == 'POST':
        
        if "pid" in request.form :
            data = Cart.get_cart(current_user.id)
            
            if(data == None): #假如購物車裡面沒有他的資料
                time = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
                input = { 
                    'aidd': 1, 
                    'time': time
                }
                Cart.add_cart(input) # 幫他加一台購物車
                data = Cart.get_cart(current_user.id) 
                
            tno = data[2] # 取得交易編號
            pid = request.values.get('pid') # 使用者想要購買的東西
            # 檢查購物車裡面有沒有商品
            input = (pid, tno)
            
            product = Shopping_Detail.check_product(input)
            # 取得商品價錢
            price = Product.get_product(pid)[2]

            # 如果購物車裡面沒有的話 把他加一個進去
            if(product == None):
                Shopping_Detail.add_product( {'id': tno, 'tno':pid, 'price':price, 'total':price} )
            else:
                # 假如購物車裡面有的話，就多加一個進去
                input = (tno, pid)
                amount = Shopping_Detail.get_amount(input)
                total = (amount+1) * int(price)
                Shopping_Detail.update_product({'amount':amount+1, 'tno':tno , 'pid':pid, 'total':total})

        elif "delete" in request.form :
            pid = request.values.get('delete')
            tno = Cart.get_cart(current_user.id)[2]
            input = (tno, pid)
            Member.delete_product(input)
            product_data = only_cart()
        
        elif "user_edit" in request.form:
            change_order()  
            return redirect(url_for('bookstore.bookstore'))
        
        elif "buy" in request.form:
            change_order()
            return redirect(url_for('bookstore.order'))

        elif "order" in request.form:
            tno = Cart.get_cart(current_user.id)[2]
            total = Shopping_Detail.get_total_money(tno)
            Cart.clear_cart(current_user.id)

            time = str(datetime.now().strftime('%Y-%m-%d %H:%M:%S'))
            input = (current_user.id, time, total, tno)
            Order_List.add_order(input)

            return render_template('complete.html', user=current_user.name)

    product_data = only_cart()
    
    if product_data == 0:
        return render_template('empty.html', user=current_user.name)
    else:
        return render_template('cart.html', data=product_data, user=current_user.name)

@store.route('/order')
def order():
    data = Cart.get_cart(current_user.id)
    tno = data[2]

    product_row = Shopping_Detail.get_shopping_detail(tno)
    product_data = []

    for i in product_row:
        pname = Product.get_name(i[1])
        product = {
            '商品編號': i[1],
            '商品名稱': pname,
            '商品價格': i[3],
            '數量': i[2]
        }
        product_data.append(product)
    
    total = Shopping_Detail.get_total(tno)[0]

    return render_template('order.html', data=product_data, total=total, user=current_user.name)

@store.route('/orderlist')
def orderlist():
    if "oid" in request.args :
        pass
    
    user_id = current_user.id

    data = Member.get_order(user_id)
    orderlist = []

    for i in data:
        temp = {
            '訂單編號': i[0],
            '訂單總價': i[3],
            '訂單時間': i[2]
        }
        orderlist.append(temp)
    
    orderdetail_row = Order_List.get_orderdetail()
    orderdetail = []

    for j in orderdetail_row:
        temp = {
            '訂單編號': j[0],
            '商品名稱': j[1],
            '商品單價': j[2],
            '訂購數量': j[3]
        }
        orderdetail.append(temp)


    return render_template('orderlist.html', data=orderlist, detail=orderdetail, user=current_user.name)

def change_order():
    data = Cart.get_cart(current_user.id)
    tno = data[2] # 使用者有購物車了，購物車的交易編號是什麼
    product_row = Shopping_Detail.get_shopping_detail(data[2])

    for i in product_row:
        
        # i[0]：交易編號 / i[1]：商品編號 / i[2]：數量 / i[3]：價格
        if int(request.form[i[1]]) != i[2]:
            Shopping_Detail.update_product({
                'amount':request.form[i[1]],
                'pid':i[1],
                'tno':tno,
                'total':int(request.form[i[1]])*int(i[3])
            })
            print('change')

    return 0


def only_cart():
    
    count = Cart.check(current_user.id)

    if(count == None):
        return 0
    
    data = Cart.get_cart(current_user.id)
    tno = data[2]
    product_row = Shopping_Detail.get_shopping_detail(tno)
    product_data = []

    for i in product_row:
        pid = i[1]
        pname = Product.get_name(i[1])
        price = i[3]
        amount = i[2]
        
        product = {
            '商品編號': pid,
            '商品名稱': pname,

bookstore/templates/bookstore.html
{% extends "frontstage.html" %}
{% block head %}
{{ super() }}
{% endblock head %}

{% block title %}商品列表{% endblock title%}

{% block content%}
<br/>

{% with messages = get_flashed_messages() %}
{% if messages %}
  
<script language="javascript">

  alert('您沒有管理員的權限喔！');

</script>

{% endif %}
{% endwith %}
<div class="book_table">

  <form class="d-flex col-sm-4" action="{{ url_for('bookstore.bookstore', keyword=1) }}">
    <div class="input-group">
    <span class="input-group-text" id="basic-addon1">
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
        <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
      </svg>
    </span>
    <input name='keyword' class="form-control me-2" type="search" placeholder="搜尋商品" aria-label="Search">
    </div>
  </form><br/>
  <form method="post" action={{ url_for('bookstore.cart') }}>
      
      {% for book in book_data %}
      {% if loop.index % 3 == 1 %}
      <div class="row">
      {% endif %}
      
        <div class="col-sm-4">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">{{book.商品名稱}}</h5>
              <p class="card-text">${{book.商品價格}}</p>
              
              <a href="{{ url_for('bookstore.bookstore', pid=book.商品編號) }}" class="btn btn-outline-primary">查看商品資訊</a>
              <button class="btn btn-outline-success" type="submit" value="{{book.商品編號}}" name="pid" >加入購物車</button>
            </div>
          </div>
        </div>

        {% if loop.index % 3 == 0 %}
        </div><br/>
        {% endif %}
            
      {% endfor %}
    </table>
  </form>


  <nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
      {% if page == 1 %}
      <li class="page-item disabled">
        <a class="page-link" href="#" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
      {% else %}
      {% if flag == 1 %}
      <li class="page-item">
        <a class="page-link" href="{{ url_for('bookstore.bookstore', keyword=keyword, page=page-1) }}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
      {% else %}
      <li class="page-item">
        <a class="page-link" href="{{ url_for('bookstore.bookstore', page=page-1) }}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
      {% endif %}
      {% endif %}
      {% for i in range(1, pagenum + 1) %}
      {% if flag == 1 %}
      <li class="page-item"><a class="page-link" href="{{ url_for('bookstore.bookstore', keyword=keyword, page=i) }}">{{i}}</a></li>
      {% else %}
      <li class="page-item"><a class="page-link" href="{{ url_for('bookstore.bookstore', page=i) }}">{{i}}</a></li>
      {% endif %}
      {% endfor %}
      {% if endpoint == 1 %}
      <li class="page-item disabled">
        <a class="page-link" href="#" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
      {% else %}
      {% if flag == 1 %}
      <li class="page-item">
        <a class="page-link" href="{{ url_for('bookstore.bookstore', keyword=keyword, page=page+1) }}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
      {% else %}
      <li class="page-item">
        <a class="page-link" href="{{ url_for('bookstore.bookstore', page=page+1) }}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
      {% endif %}
      {% endif %}
    </ul>
  </nav>



</div>

{% endblock content%}

bookstore/templates/cart.html
{% extends "frontstage.html" %}
{% block head %}
{{ super() }}
{% endblock head %}

{% block title %}購物車清單{% endblock title%}

{% block content %}

{% with messages = get_flashed_messages() %}
{% if messages[0] == 'No permission' %}
  
<script language="javascript">
  alert('您沒有使用者的權限喔！');
</script>

{% endif %}
{% endwith %}

<br/>
<div class="container-xl">
  <br/>
  <form method="post" action={{ url_for('bookstore.cart') }}>
    <table class="table table-bordered">
      <tr>
        <th><center>商品編號</center></th>
        <th><center>商品名稱</center></th>
        <th><center>商品價格</center></th>
        <th><center>數量</center></th>
        <th><center>商品操作</center></th>
      </tr>
      {% for book in data %}
      <tr>
        <td> <center>{{ book.商品編號 }}</center></td>
        <td> <center>{{ book.商品名稱 }}</center></td>
        <td> <center>{{ book.商品價格 }}</center></td>
        <td width="20%">
          <center>
            <input class="form-control" type="number" onkeyup="value=value.replace(/[^\d]/g,'')" min="1" value="{{ book.數量 }}" name="{{ book.商品編號 }}">

          </center>
        </td>
        <td>
          <center>
            <button class="btn btn-danger" type="submit" value="{{book.商品編號}}" name="delete" onclick="return (confirm('你確定要刪除 \'{{ book.商品名稱 }}\' 嗎？'))">
              刪除
            </button>
          </center>
      </td>
      </tr>
      {% endfor %}
    </table>
    <center>
      <div class="option">
        <button class="btn btn-primary" type="submit" value="edit" name="user_edit" >繼續購物</button>
        <button class="btn btn-success" type="submit" value="edit" name="buy" >直接結帳</button>
      </div>
    </center>


  </form>

</div>

{% endblock content%}

bookstore/templates/complete.html
{% extends "frontstage.html" %}
{% block head %}
{{ super() }}
{% endblock head %}

{% block title %} 下單完成 {% endblock title%}

{% block content %}

{% with messages = get_flashed_messages() %}
{% if messages[0] == 'No permission' %}
  
<script language="javascript">
  alert('您沒有使用者的權限喔！');
</script>

{% endif %}
{% endwith %}

<br/>

<div class="container-xxl">
  <center>
    <img width="30%" height="30%" src="../static/img/order_success.png">
  </center>
  <center>
    <h4>下單完成！</h4>
  </center>
  <center>
    
      <a href="{{ url_for('bookstore.bookstore') }}">
        <button class="btn btn-outline-success" style="width:30%;">
          回書店
        </button>
      </a>
      
  </center>
  
  
</div>

{% endblock content%}

bookstore/templates/empty.html
{% extends "frontstage.html" %}
{% block head %}
{{ super() }}
{% endblock head %}

{% block title %}購物車清單{% endblock title%}

{% block content %}

{% with messages = get_flashed_messages() %}
{% if messages[0] == 'No permission' %}
  
<script language="javascript">
  alert('您沒有使用者的權限喔！');
</script>

{% endif %}
{% endwith %}

<br/>

<div class="container-xxl">
  <center>
    <img width="50%" height="50%" src="../static/img/empty_cart.png">
  </center>
  <center>
    
      <a href="{{ url_for('bookstore.bookstore') }}">
        <button class="btn btn-outline-success" style="width:30%;">
          繼續購物
        </button>
      </a>
      
  </center>
  
  
</div>

{% endblock content%}

bookstore/templates/frontstage.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link href="../static/offcanvas.css" rel="stylesheet">
    <link rel="icon" href="../static/img/weblogo.ico" type="image/x-icon">
    <script src="../static/offcanvas.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
    <title> {% block title%}{% endblock title%} </title>
    {% endblock head %}
</head>

<style>
    main > .container {
        padding: 60px 15px 0;
      }

    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }
  
    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
  </style>
<body class="bg-light">
    <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark">
        <div class="container-fluid">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="white" class="bi bi-easel2" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M8 0a.5.5 0 0 1 .447.276L8.81 1h4.69A1.5 1.5 0 0 1 15 2.5V11h.5a.5.5 0 0 1 0 1h-2.86l.845 3.379a.5.5 0 0 1-.97.242L12.11 14H3.89l-.405 1.621a.5.5 0 0 1-.97-.242L3.36 12H.5a.5.5 0 0 1 0-1H1V2.5A1.5 1.5 0 0 1 2.5 1h4.691l.362-.724A.5.5 0 0 1 8 0ZM2 11h12V2.5a.5.5 0 0 0-.5-.5h-11a.5.5 0 0 0-.5.5V11Zm9.61 1H4.39l-.25 1h7.72l-.25-1Z"/>
            </svg>
            <a class="navbar-brand" href="#">&nbsp;中山網路書店</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('bookstore.bookstore') }}">商品導覽</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('bookstore.cart') }}">購物車</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('bookstore.orderlist') }}">歷史訂單</a>
                    </li>
                </ul>

                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="white" class="bi bi-person-circle" viewBox="0 0 18 18">
                    <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                    <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
                </svg>

                <ul class="navbar-nav me-3 mb-2 mb-lg-0">
                    <li style="color:white;list-style-type:none">使用者：{{user}}</li>
                </ul>

                <a href="{{ url_for('api.logout') }}"><button class="btn btn-outline-danger" type="submit">登出系統</button></a>
            </div>
        </div>
    </nav>
    <br/><br/>
    {% block content %}
    {% endblock content %}
</body>
</html>

bookstore/templates/order.html
{% extends "frontstage.html" %}
{% block head %}
{{ super() }}
{% endblock head %}

{% block title %}BookStore{% endblock title%}

{% block content%}
<br/>
<div class="container-xl">
  <form method="post" action={{ url_for('bookstore.cart') }}>
    <table class="table table-bordered">
      <tr>
        <th><center>商品編號</center></th>
        <th><center>商品名稱</center></th>
        <th><center>商品價格</center></th>
        <th><center>數量</center></th>
      </tr>
      {% for book in data %}
      <tr>
        <td> <center>{{ book.商品編號 }}</center></td>
        <td> <center>{{ book.商品名稱 }}</center></td>
        <td> <center>{{ book.商品價格 }}</center></td>
        <td width="20%">
          <center>
            {{ book.數量 }}
          </center>
        </td>
      </tr>
      {% endfor %}
    </table>
    <div class="col align-self-end">
      
    </div>
    <div class="container-xxl" style="text-align: right;">
      <div class="row">
        <div class="col align-self-start">
 
        </div>
        <div class="col align-self-center">

        </div>
        <div class="col align-self-end">
          <b class="ml-50">訂單總價：{{ total }} 元</b>
        </div>
      </div>
    </div>

    
    <center> 
      <div class="option">
        <a href="{{ url_for('bookstore.cart') }}"><button class="btn btn-primary" type="submit" >回購物車</button></a>
        <button class="btn btn-success" type="submit" value="order" name="order">下訂單</button>
    </div>
    </center>

  </form>
</div>
{% endblock content%}

bookstore/templates/orderlist.html
{% extends "frontstage.html" %}
{% block head %}
{{ super() }}
{% endblock head %}

{% block title %}BookStore{% endblock title%}

{% block content %}
<!-- <form method="post" action="#"> -->
  {% for i in data %}
  <div class="modal fade" id="staticBackdrop{{i.訂單編號}}" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
      <div class="modal-dialog">
          <div class="modal-content">
              <div class="modal-header">
                  <h5 class="modal-title" id="staticBackdropLabel">訂單細項列表</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                  <div class="mb-3">
                    <table class="table table-bordered">
                      <tr>
                        <th><center>商品名稱</center></th>
                        <th><center>商品單價</center></th>
                        <th><center>訂購數量</center></th>
                      </tr>
                      
                      {% for j in detail %}
                      {% if j.訂單編號 == i.訂單編號 %}
                      <tr>
                        <td> <center>{{ j.商品名稱 }}</center></td>
                        <td> <center>{{ j.商品單價 }}</center></td>
                        <td> <center>{{ j.訂購數量 }}</center></td>
                      </tr>
                      {% endif %}
                      {% endfor %}
                    </table>
                  </div>
              </div>
              <div class="modal-footer">
                  <button type="button" class="btn btn-outline-success" data-bs-dismiss="modal" style="width:30%;">回訂單</button>
              </div>
          </div>
      </div>
  </div>
  {% endfor %}
<!-- </form> -->



<br/>
<div class="container-xl">
  <form method="post" action={{ url_for('bookstore.orderlist') }}>
    <table class="table table-bordered">
      <tr>
        <th><center>訂單編號</center></th>
        <th><center>訂單總價</center></th>
        <th><center>訂單時間</center></th>
        <th><center>查看訂單</center></th>
      </tr>
      {% for i in data %}
      <tr>
        <td> <center>{{ i.訂單編號 }}</center></td>
        <td> <center>{{ i.訂單總價 }}</center></td>
        <td> <center>{{ i.訂單時間 }}</center></td>
        <td width="20%">
          <center>
            <button type="button" class="btn btn-outline-success" data-bs-toggle="modal" data-bs-target="#staticBackdrop{{i.訂單編號}}">
              查看訂單細項
            </button>
          </center>
        </td>
      </tr>
      {% endfor %}
    </table>

  </form>
</div>

{% endblock content %}

bookstore/templates/product.html
{% extends "frontstage.html" %}
{% block head %}
{{ super() }}
{% endblock head %}

{% block title %}BookStore{% endblock title%}

{% block content %}

{% set temp = 'product/' + data.商品圖片 %}

<br/>
<div class="row">
<div class="card" style="width: 20rem;margin-left:5%">
  <img src={{ url_for('static', filename = temp  ) }} class="card-img-top">
  <div class="card-body">
    <h5 class="card-title">{{ data.商品名稱 }}</h5>
    <p class="card-text"></p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item"><b>商品類別</b>&nbsp;&nbsp;{{ data.類別 }}</li>
    <li class="list-group-item"><b>商品單價</b>&nbsp;&nbsp;{{ data.單價 }}</li>
  </ul>
  <div class="card-body">
    <a href="{{ url_for('bookstore.bookstore') }}" class="btn btn-outline-primary">回商品列表</a>
  </div>
</div>


<div class="col-sm-6">
  <form method="post" action={{ url_for('bookstore.cart') }}>
<div class="card" style="margin-top:10%">
  <h5 class="card-header">商品介紹</h5>
  <div class="card-body">
    <p class="card-text">
      {{data.商品敘述}}
    </p>
    <button class="btn btn-outline-success" type="submit" value="{{data.商品編號}}" name="pid">加入購物車</a>
  </div>
</div>
</form>
</div>


</div>


{% endblock content%}